export const ClassNames = {
  root: "space-y-6 animate-fade-in-up",

  pageHeader: "flex flex-col sm:flex-row sm:items-center justify-between gap-2",
  pageTitle: "text-white text-2xl font-bold",
  pageSub: "text-gray-400 text-sm mt-1",
  monthBadge: "text-xs text-gray-500 mt-1",

  // Comparison banner
  bannerGrid: "grid grid-cols-1 sm:grid-cols-3 gap-4",
  bannerCard: "bg-gray-800/50 border border-gray-700/50 rounded-2xl p-5",
  bannerIcon: "w-9 h-9 rounded-xl flex items-center justify-center mb-3",
  bannerIconRed: "w-9 h-9 rounded-xl bg-red-500/15 flex items-center justify-center mb-3",
  bannerIconGreen: "w-9 h-9 rounded-xl bg-emerald-500/15 flex items-center justify-center mb-3",
  bannerIconAmber: "w-9 h-9 rounded-xl bg-amber-500/15 flex items-center justify-center mb-3",
  bannerIconBlue: "w-9 h-9 rounded-xl bg-blue-500/15 flex items-center justify-center mb-3",
  bannerLabel: "text-gray-400 text-xs mb-1",
  bannerValue: "text-white font-bold text-xl",
  bannerValueRed: "text-red-400 font-bold text-xl",
  bannerValueGreen: "text-emerald-400 font-bold text-xl",
  bannerValueAmber: "text-amber-400 font-bold text-xl",
  bannerSub: "text-gray-500 text-xs mt-1",
  bannerVerdictAbove: "inline-flex items-center gap-1 mt-2 px-2.5 py-1 rounded-lg bg-red-500/10 text-red-400 text-xs font-medium",
  bannerVerdictBelow: "inline-flex items-center gap-1 mt-2 px-2.5 py-1 rounded-lg bg-emerald-500/10 text-emerald-400 text-xs font-medium",
  bannerVerdictEqual: "inline-flex items-center gap-1 mt-2 px-2.5 py-1 rounded-lg bg-gray-700 text-gray-400 text-xs font-medium",

  // Category trends grid
  trendsGrid: "grid grid-cols-1 lg:grid-cols-2 gap-6",
  trendsCard: "bg-gray-800/50 border border-gray-700/50 rounded-2xl p-6",
  trendsHeader: "flex items-center gap-2 mb-5",
  trendsHeaderLeft: "flex items-center gap-2 flex-1",
  trendsTitle: "text-white font-semibold flex-1",
  trendsToggleBtn: "flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg border border-gray-600 text-gray-400 hover:text-white hover:border-gray-500 text-xs transition-colors",
  trendsToggleBtnActive: "flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg border border-emerald-600/50 bg-emerald-500/10 text-emerald-400 text-xs transition-colors",
  trendsList: "space-y-3",
  trendsEmpty: "text-gray-500 text-sm text-center py-8",
  trendsChartWrap: "overflow-hidden transition-all duration-300",
  trendsChartDivider: "border-t border-gray-700/50 mt-4 pt-4",

  trendRow: "flex items-center gap-3",
  trendDot: "w-2.5 h-2.5 rounded-full flex-shrink-0",
  trendName: "text-gray-300 text-sm flex-1 truncate",
  trendAmounts: "text-right flex-shrink-0",
  trendPctUp: "text-red-400 text-sm font-semibold",
  trendPctDown: "text-emerald-400 text-sm font-semibold",
  trendAmountSub: "text-gray-600 text-xs",
  trendBarWrap: "mt-1 h-1 rounded-full overflow-hidden bg-gray-700/60",
  trendBarUp: "h-full rounded-full bg-red-500/60 transition-all duration-500",
  trendBarDown: "h-full rounded-full bg-emerald-500/60 transition-all duration-500",
  trendArrowUp: "w-3.5 h-3.5 text-red-400 flex-shrink-0",
  trendArrowDown: "w-3.5 h-3.5 text-emerald-400 flex-shrink-0",

  // Inflation chart
  inflacionCard: "bg-gray-800/50 border border-gray-700/50 rounded-2xl p-6",
  inflacionHeader: "flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-6",
  inflacionTitle: "text-white font-semibold",
  inflacionHeaderRight: "flex items-center gap-3",
  inflacionBadge: "px-2.5 py-1 rounded-lg bg-amber-500/10 text-amber-400 text-xs font-medium",
  inflacionStats: "flex items-center gap-4",
  inflacionStatLabel: "text-gray-400 text-xs",
  inflacionStatValue: "text-white text-sm font-semibold",
  inflacionLoading: "h-56 flex items-center justify-center",
  spinner: "w-8 h-8 border-2 border-emerald-500 border-t-transparent rounded-full animate-spin",
  inflacionError: "h-56 flex items-center justify-center text-gray-500 text-sm",

  skeletonCard: "bg-gray-800/50 border border-gray-700/50 rounded-2xl p-5 animate-pulse",
  skeletonBar: "h-4 bg-gray-700 rounded-lg",
  skeletonBarSm: "h-3 bg-gray-700 rounded-lg mt-2",
}
