export const S = {
  root: "space-y-6",
  pageHeader: "flex items-center justify-between",
  pageTitle: "text-white text-2xl font-bold",
  pageSub: "text-gray-400 text-sm mt-1",
  newBtn: "flex items-center gap-2 px-4 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-white text-sm font-medium transition-colors shadow-lg shadow-emerald-500/20",
  summaryGrid: "grid grid-cols-1 sm:grid-cols-3 gap-4",
  summaryCard: "bg-gray-800/50 border border-gray-700/50 rounded-2xl p-5",
  summaryLabel: "text-gray-400 text-sm mb-1",
  summaryValueWhite: "text-white text-2xl font-bold",
  summaryValueGreen: "text-emerald-400 text-2xl font-bold",
  summaryValueAmber: "text-amber-400 text-2xl font-bold",
  skeletonList: "space-y-4",
  skeletonCard: "h-40 bg-gray-800 rounded-2xl animate-pulse",
  emptyWrap: "text-center py-20 text-gray-500",
  emptyCreateBtn: "px-5 py-2.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-white text-sm font-medium transition-colors",
  goalsGrid: "grid grid-cols-1 lg:grid-cols-2 gap-4",
  goalCardCompleted: "bg-gray-800/50 border border-emerald-500/40 rounded-2xl p-6 transition-all",
  goalCardNormal: "bg-gray-800/50 border border-gray-700/50 rounded-2xl p-6 transition-all",
  goalTopRow: "flex items-start justify-between mb-4",
  goalIconRow: "flex items-center gap-3",
  goalIconWrap: "w-10 h-10 rounded-xl flex items-center justify-center",
  goalName: "text-white font-semibold",
  goalDesc: "text-gray-500 text-xs mt-0.5",
  goalCardActions: "flex items-center gap-1",
  goalEditBtn: "p-1.5 rounded-lg text-gray-500 hover:text-blue-400 hover:bg-blue-500/10 transition-colors",
  deleteConfirmWrap: "flex items-center gap-1",
  deleteConfirmBtn: "px-2 py-1 rounded-md text-xs bg-red-500/20 text-red-400 hover:bg-red-500/30",
  deleteConfirmNoBtn: "px-2 py-1 rounded-md text-xs bg-gray-700 text-gray-400",
  goalDeleteBtn: "p-1.5 rounded-lg text-gray-500 hover:text-red-400 hover:bg-red-500/10 transition-colors",
  currencyBadge: "inline-flex items-center px-2 py-0.5 rounded-md bg-amber-500/15 text-amber-400 text-xs font-medium mb-3",
  progressSection: "mb-3",
  progressRow: "flex justify-between text-sm mb-1.5",
  progressCurrent: "text-white font-semibold",
  progressTarget: "text-gray-400",
  progressBar: "h-3 bg-gray-700 rounded-full overflow-hidden",
  progressFill: "h-full rounded-full transition-all duration-700",
  progressMeta: "flex justify-between mt-1.5",
  progressCompleted: "text-emerald-400 text-xs font-semibold",
  progressRemaining: "text-gray-500 text-xs",
  arsEquivalent: "text-gray-600 text-xs mt-1",
  addInputWrap: "flex gap-2 mt-2",
  addInput: "flex-1 px-3 py-2 bg-gray-700 border border-gray-600 rounded-xl text-white text-sm focus:outline-none focus:border-emerald-500",
  addOkBtn: "px-3 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-white text-sm font-medium",
  addCancelBtn: "px-3 py-2 rounded-xl bg-gray-700 text-gray-400 text-sm",
  addSavingBtn: "flex-1 flex items-center justify-center gap-1.5 py-2 rounded-xl border border-dashed border-gray-600 text-gray-400 hover:border-emerald-500 hover:text-emerald-400 text-sm transition-colors",
  modalOverlay: "fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4",
  modalBox: "bg-gray-800 border border-gray-700 rounded-2xl p-6 w-full max-w-md shadow-xl",
  modalHeader: "flex items-center justify-between mb-5",
  modalTitle: "text-white font-semibold text-lg",
  modalCloseBtn: "text-gray-500 hover:text-white",
  modalFields: "space-y-4",
  fieldLabel: "text-gray-400 text-sm mb-1.5 block",
  currencyToggleWrap: "flex rounded-xl overflow-hidden border border-gray-700",
  currencyBtnArsActive: "flex-1 py-2.5 text-sm font-medium transition-colors bg-emerald-500 text-white",
  currencyBtnUsdActive: "flex-1 py-2.5 text-sm font-medium transition-colors bg-amber-500 text-white",
  currencyBtnInactive: "flex-1 py-2.5 text-sm font-medium transition-colors text-gray-400 hover:text-white",
  textInput: "w-full px-4 py-2.5 bg-gray-700/50 border border-gray-600 rounded-xl text-white placeholder-gray-500 focus:outline-none focus:border-emerald-500 text-sm",
  amountGrid: "grid grid-cols-2 gap-3",
  colorRow: "flex gap-2 flex-wrap",
  colorSwatch: "w-7 h-7 rounded-full transition-transform hover:scale-110",
  modalActions: "flex gap-3 mt-6",
  cancelBtn: "flex-1 py-2.5 rounded-xl border border-gray-600 text-gray-300 hover:bg-gray-700 text-sm transition-colors",
  saveBtn: "flex-1 py-2.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-white text-sm font-medium transition-colors disabled:opacity-50",
  toast: "fixed bottom-6 right-6 flex items-center gap-2 px-4 py-3 rounded-xl shadow-xl text-sm font-medium z-50 bg-emerald-500 text-white",
}
