export const S = {
  root: "space-y-6",
  pageHeader: "flex flex-col sm:flex-row sm:items-center justify-between gap-4",
  pageTitle: "text-white text-2xl font-bold",
  pageSub: "text-gray-400 text-sm mt-1",
  headerActions: "flex items-center gap-2",
  exportBtn: "flex items-center gap-2 px-3 py-2 rounded-xl border border-gray-600 text-gray-300 hover:bg-gray-700/50 text-sm transition-colors",
  exportBtnLabel: "hidden sm:inline",
  summaryGrid: "grid grid-cols-2 lg:grid-cols-4 gap-4",
  summaryCard: "bg-gray-800/50 border border-gray-700/50 rounded-2xl p-4",
  summaryIconIngreso: "w-8 h-8 rounded-lg bg-emerald-500/15 flex items-center justify-center mb-2",
  summaryIconGasto: "w-8 h-8 rounded-lg bg-red-500/15 flex items-center justify-center mb-2",
  summaryIconBlue: "w-8 h-8 rounded-lg bg-blue-500/15 flex items-center justify-center mb-2",
  summaryIconAmber: "w-8 h-8 rounded-lg bg-amber-500/15 flex items-center justify-center mb-2",
  summaryLabel: "text-gray-400 text-xs",
  summaryValueIngreso: "text-emerald-400 font-bold text-lg mt-0.5",
  summaryValueGasto: "text-red-400 font-bold text-lg mt-0.5",
  summaryValueBalancePos: "font-bold text-lg mt-0.5 text-blue-400",
  summaryValueBalanceNeg: "font-bold text-lg mt-0.5 text-orange-400",
  summaryValueAmber: "text-amber-400 font-bold text-lg mt-0.5",
  chartCard: "bg-gray-800/50 border border-gray-700/50 rounded-2xl p-6",
  chartHeader: "flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6",
  chartTitle: "text-white font-semibold",
  chartControls: "flex items-center gap-2",
  monthsSelect: "px-3 py-1.5 bg-gray-700/50 border border-gray-600 rounded-lg text-gray-300 text-sm focus:outline-none focus:border-emerald-500 transition-colors",
  chartTypeTabs: "flex bg-gray-700/50 rounded-lg p-1",
  chartTypeBtnActive: "p-1.5 rounded-md transition-colors bg-emerald-500/20 text-emerald-400",
  chartTypeBtnInactive: "p-1.5 rounded-md transition-colors text-gray-400 hover:text-white",
  chartLoading: "h-72 flex items-center justify-center",
  spinner: "w-8 h-8 border-2 border-emerald-500 border-t-transparent rounded-full animate-spin",
  bottomGrid: "grid grid-cols-1 lg:grid-cols-2 gap-6",
  pieCard: "bg-gray-800/50 border border-gray-700/50 rounded-2xl p-6",
  pieHeader: "flex items-center justify-between mb-5",
  pieHeaderLeft: "flex items-center gap-2",
  pieTabs: "flex bg-gray-700/50 rounded-lg p-1",
  pieBtnGastoActive: "px-2.5 py-1 rounded-md text-xs font-medium transition-colors bg-red-500/20 text-red-400",
  pieBtnIngresoActive: "px-2.5 py-1 rounded-md text-xs font-medium transition-colors bg-emerald-500/20 text-emerald-400",
  pieBtnInactive: "px-2.5 py-1 rounded-md text-xs font-medium transition-colors text-gray-400 hover:text-white",
  pieLoading: "h-64 flex items-center justify-center",
  monthlyCard: "bg-gray-800/50 border border-gray-700/50 rounded-2xl p-6",
  monthlyTitle: "text-white font-semibold mb-5",
  monthlyList: "space-y-3",
  monthlyRow: "",
  monthlyMeta: "flex items-center justify-between mb-1",
  monthlyLabel: "text-gray-300 text-sm capitalize",
  monthlyBalancePos: "text-sm font-medium text-emerald-400",
  monthlyBalanceNeg: "text-sm font-medium text-red-400",
  monthlyBar: "h-1.5 bg-gray-700 rounded-full overflow-hidden",
  monthlyFillGood: "h-full rounded-full transition-all duration-500 bg-emerald-500",
  monthlyFillWarn: "h-full rounded-full transition-all duration-500 bg-amber-500",
  monthlyFillBad: "h-full rounded-full transition-all duration-500 bg-red-500",
  monthlySubRow: "flex justify-between mt-0.5",
  monthlySubText: "text-gray-600 text-xs",
}
