export const ClassNames = {
  overlay: "fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm",
  modal: "bg-gray-800 border border-gray-700 rounded-2xl w-full max-w-md shadow-2xl",
  header: "flex items-center justify-between px-6 py-4 border-b border-gray-700",
  headerTitle: "text-white font-semibold text-lg",
  closeBtn: "p-1.5 rounded-lg text-gray-400 hover:text-white hover:bg-gray-700 transition-colors",
  form: "p-6 space-y-5",
  label: "block text-sm font-medium text-gray-300 mb-2",
  input: "w-full px-4 py-2.5 bg-gray-700/50 border border-gray-600 rounded-xl text-white placeholder-gray-500 focus:outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500/30 transition-colors",
  typeGrid: "grid grid-cols-2 gap-2",
  typeBtnBase: "py-2.5 px-4 rounded-xl text-sm font-medium transition-all",
  typeBtnIngreso: "bg-emerald-500/20 text-emerald-400 border border-emerald-500/50",
  typeBtnGasto: "bg-red-500/20 text-red-400 border border-red-500/50",
  typeBtnInactive: "bg-gray-700/50 text-gray-400 border border-transparent hover:border-gray-600",
  colorSwatchWrap: "flex flex-wrap gap-2 mb-3",
  colorSwatchActive: "ring-2 ring-white ring-offset-2 ring-offset-gray-800 scale-110",
  colorSwatchInactive: "hover:scale-105",
  colorSwatchBase: "w-8 h-8 rounded-lg transition-all",
  colorPickerRow: "flex items-center gap-3",
  colorPreview: "w-8 h-8 rounded-lg border border-gray-600 flex-shrink-0",
  colorInput: "w-full h-9 bg-gray-700/50 border border-gray-600 rounded-lg cursor-pointer",
  error: "text-red-400 text-sm bg-red-500/10 border border-red-500/20 rounded-lg px-3 py-2",
  actions: "flex gap-3 pt-1",
  cancelBtn: "flex-1 py-2.5 px-4 rounded-xl border border-gray-600 text-gray-300 hover:bg-gray-700/50 transition-colors text-sm font-medium",
  submitBtn: "flex-1 py-2.5 px-4 rounded-xl bg-emerald-500 hover:bg-emerald-400 disabled:opacity-60 text-white font-medium text-sm transition-colors flex items-center justify-center gap-2",
}
