export const ClassNames = {
  root: "space-y-6",
  pageHeader: "flex flex-col sm:flex-row sm:items-center justify-between gap-4",
  pageTitle: "text-white text-2xl font-bold",
  pageSub: "text-gray-400 text-sm mt-1",
  newBtn: "flex items-center gap-2 px-4 py-2.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-white text-sm font-medium transition-colors shadow-lg shadow-emerald-500/20 self-start",
  filterRow: "flex gap-2",
  filterBtnAllActive: "bg-gray-700 text-white border border-gray-600",
  filterBtnIngresoActive: "bg-emerald-500/20 text-emerald-400 border border-emerald-500/40",
  filterBtnGastoActive: "bg-red-500/20 text-red-400 border border-red-500/40",
  filterBtnInactive: "text-gray-400 hover:text-white border border-transparent",
  filterBtnBase: "px-4 py-2 rounded-xl text-sm font-medium transition-all",
  filterBtnCount: "ml-2 text-xs opacity-60",
  skeletonGrid: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4",
  skeletonCard: "bg-gray-800/50 border border-gray-700/50 rounded-2xl p-5 animate-pulse",
  skeletonLine1: "h-5 bg-gray-700 rounded w-3/4 mb-3",
  skeletonLine2: "h-4 bg-gray-700 rounded w-1/2",
  sectionTitleIngreso: "text-emerald-400 font-semibold text-sm uppercase tracking-wider mb-3",
  sectionTitleGasto: "text-red-400 font-semibold text-sm uppercase tracking-wider mb-3 mt-2",
  catGrid: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4",
  emptyWrap: "flex flex-col items-center justify-center py-16 text-center",
  emptyIconWrap: "w-16 h-16 rounded-2xl bg-gray-800 border border-gray-700 flex items-center justify-center mb-4",
  emptyTitle: "text-gray-400 font-medium",
  emptySub: "text-gray-600 text-sm mt-1",
  card: "bg-gray-800/50 border border-gray-700/50 rounded-2xl p-5 hover:border-gray-600 transition-all group",
  cardTop: "flex items-start justify-between",
  cardIconRow: "flex items-center gap-3",
  cardIconWrap: "w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0 shadow-lg",
  cardIconDot: "w-4 h-4 rounded-md",
  cardName: "text-white font-medium",
  cardTypeIngreso: "text-xs mt-0.5 inline-block text-emerald-400",
  cardTypeGasto: "text-xs mt-0.5 inline-block text-red-400",
  cardActions: "flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity",
  editBtn: "p-1.5 rounded-lg text-gray-500 hover:text-blue-400 hover:bg-blue-500/10 transition-colors",
  deleteConfirmWrap: "flex items-center gap-1",
  deleteConfirmYes: "px-2 py-1 rounded-md text-xs bg-red-500/20 text-red-400 hover:bg-red-500/30 transition-colors",
  deleteConfirmNo: "px-2 py-1 rounded-md text-xs bg-gray-700 text-gray-400 hover:bg-gray-600 transition-colors",
  deleteBtn: "p-1.5 rounded-lg text-gray-500 hover:text-red-400 hover:bg-red-500/10 transition-colors",
  colorBarWrap: "mt-3 flex items-center gap-2",
  colorBar: "h-1.5 flex-1 rounded-full opacity-60",
  colorHex: "text-gray-600 text-xs font-mono",
}
