export const S = {
  root: "space-y-6",
  welcomeTitle: "text-white text-2xl font-bold capitalize",
  welcomeSub: "text-gray-400 text-sm mt-1",
  welcomeHighlight: "text-emerald-400 font-medium capitalize",
  statsGrid: "grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4",
  statCard: "bg-gray-800/50 border border-gray-700/50 rounded-2xl p-5",
  statCardHeader: "flex items-center justify-between mb-3",
  statIconIngreso: "w-10 h-10 rounded-xl bg-emerald-500/15 flex items-center justify-center",
  statIconGasto: "w-10 h-10 rounded-xl bg-red-500/15 flex items-center justify-center",
  statIconAmber: "w-10 h-10 rounded-xl bg-amber-500/15 flex items-center justify-center",
  statIconBluePos: "w-10 h-10 rounded-xl bg-blue-500/15 flex items-center justify-center",
  statIconOrangeNeg: "w-10 h-10 rounded-xl bg-orange-500/15 flex items-center justify-center",
  statChangePos: "flex items-center gap-1 text-xs font-medium text-emerald-400",
  statChangeNeg: "flex items-center gap-1 text-xs font-medium text-red-400",
  statLabel: "text-gray-400 text-sm",
  statValue: "text-white text-2xl font-bold mt-1",
  statValueAmber: "text-amber-400 text-2xl font-bold mt-1",
  statValueBalancePos: "text-2xl font-bold mt-1 text-blue-400",
  statValueBalanceNeg: "text-2xl font-bold mt-1 text-orange-400",
  statSub: "text-gray-500 text-xs mt-1",
  topCatCard: "bg-gray-800/50 border border-gray-700/50 rounded-2xl p-6",
  topCatHeader: "flex items-center justify-between mb-5",
  topCatTitle: "text-white font-semibold",
  topCatMonth: "text-gray-500 text-xs capitalize",
  topCatGrid: "grid grid-cols-1 sm:grid-cols-2 gap-4",
  topCatRow: "space-y-1.5",
  topCatMeta: "flex items-center justify-between text-sm",
  topCatLeft: "flex items-center gap-2 min-w-0",
  topCatRank: "text-gray-500 text-xs w-4 flex-shrink-0",
  topCatColorDot: "w-2.5 h-2.5 rounded-full flex-shrink-0",
  topCatName: "text-gray-300 truncate",
  topCatRight: "text-right flex-shrink-0 ml-2",
  topCatAmount: "text-white font-semibold",
  topCatPct: "text-gray-500 text-xs ml-1.5",
  topCatBar: "h-1.5 bg-gray-700 rounded-full overflow-hidden",
  topCatBarFill: "h-full rounded-full transition-all duration-700",
  topCatFooter: "mt-4 pt-4 border-t border-gray-700/50 flex justify-between text-sm",
  topCatFooterLabel: "text-gray-500",
  topCatFooterValue: "text-red-400 font-semibold",
  alertsCard: "bg-gray-800/50 border border-gray-700/50 rounded-2xl p-6",
  alertsHeader: "flex items-center gap-2 mb-5",
  alertsTitle: "text-white font-semibold",
  alertsMonth: "ml-auto text-gray-500 text-xs capitalize",
  alertsGrid: "grid grid-cols-1 sm:grid-cols-2 gap-3",
  alertItemSpike: "border border-red-500/30 bg-red-500/5 rounded-xl p-4 space-y-2",
  alertItemHighShare: "border border-amber-500/30 bg-amber-500/5 rounded-xl p-4 space-y-2",
  alertItemNew: "border border-blue-500/30 bg-blue-500/5 rounded-xl p-4 space-y-2",
  alertItemRow: "flex items-center gap-2",
  alertItemDot: "w-2.5 h-2.5 rounded-full flex-shrink-0",
  alertItemCat: "text-white font-medium text-sm",
  alertIconSpike: "w-4 h-4 ml-auto flex-shrink-0 text-red-400",
  alertIconHighShare: "w-4 h-4 ml-auto flex-shrink-0 text-amber-400",
  alertIconNew: "w-4 h-4 ml-auto flex-shrink-0 text-blue-400",
  alertMsgSpike: "text-xs font-semibold text-red-400",
  alertMsgHighShare: "text-xs font-semibold text-amber-400",
  alertMsgNew: "text-xs font-semibold text-blue-400",
  alertAmounts: "flex items-center justify-between text-xs text-gray-400",
  alertSuggestion: "text-gray-500 text-xs",
  bottomGrid: "grid grid-cols-1 lg:grid-cols-3 gap-6",
  recentCard: "lg:col-span-2 bg-gray-800/50 border border-gray-700/50 rounded-2xl p-6",
  recentHeader: "flex items-center justify-between mb-5",
  recentTitle: "text-white font-semibold",
  recentLink: "text-emerald-400 hover:text-emerald-300 text-sm font-medium transition-colors",
  emptyWrap: "flex flex-col items-center justify-center py-10 text-center",
  emptyText: "text-gray-500 text-sm",
  emptyLink: "mt-3 text-emerald-400 hover:text-emerald-300 text-sm font-medium transition-colors",
  txList: "space-y-3",
  txRow: "flex items-center gap-3 p-3 rounded-xl hover:bg-gray-700/30 transition-colors",
  txIconWrap: "w-9 h-9 rounded-xl flex items-center justify-center flex-shrink-0",
  txIconDot: "w-2.5 h-2.5 rounded-full",
  txMeta: "flex-1 min-w-0",
  txDesc: "text-white text-sm font-medium truncate",
  txSub: "text-gray-500 text-xs",
  txAmountIngreso: "text-sm font-semibold flex-shrink-0 text-emerald-400",
  txAmountGasto: "text-sm font-semibold flex-shrink-0 text-red-400",
  quickStats: "space-y-4",
  thisMonthCard: "bg-gray-800/50 border border-gray-700/50 rounded-2xl p-5",
  thisMonthTitle: "text-white font-semibold mb-4",
  thisMonthInner: "space-y-3",
  progressMeta: "flex justify-between text-sm mb-1.5",
  progressLabel: "text-gray-400",
  progressValue: "text-gray-300",
  progressBar: "h-2 bg-gray-700 rounded-full overflow-hidden",
  progressFillGood: "h-full rounded-full transition-all duration-700 bg-emerald-500",
  progressFillBad: "h-full rounded-full transition-all duration-700 bg-red-500",
  miniGrid: "grid grid-cols-2 gap-3 pt-2",
  miniCard: "bg-gray-700/30 rounded-xl p-3",
  miniLabel: "text-gray-400 text-xs mb-1",
  miniValue: "text-white font-bold text-xl",
  miniSurplusPos: "font-bold text-lg text-emerald-400",
  miniSurplusNeg: "font-bold text-lg text-gray-500",
  dolarCard: "bg-gray-800/50 border border-gray-700/50 rounded-2xl p-5",
  dolarHeader: "flex items-center justify-between mb-3",
  dolarTitle: "text-white font-semibold",
  dolarLink: "text-emerald-400 hover:text-emerald-300 text-xs font-medium transition-colors",
  dolarRow: "flex justify-between items-end",
  dolarBuyLabel: "text-gray-400 text-xs",
  dolarBuyValue: "text-white font-semibold",
  dolarSellLabel: "text-gray-400 text-xs",
  dolarSellValue: "text-emerald-400 font-bold text-xl",
}
