export const ClassNames = {
  root: "space-y-6",
  welcomeTitle: "text-2xl font-bold capitalize bg-gradient-to-r from-white to-gray-400 bg-clip-text text-transparent",
  welcomeSub: "text-gray-500 text-sm mt-1",
  welcomeHighlight: "text-emerald-400 font-semibold capitalize",
  statsGrid: "grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4",

  // Colored gradient stat cards
  statCardIngreso: "bg-gradient-to-br from-emerald-500/10 to-gray-900 border border-emerald-500/20 rounded-2xl p-5 hover:border-emerald-500/40 transition-all duration-300",
  statCardGasto:   "bg-gradient-to-br from-red-500/10 to-gray-900 border border-red-500/20 rounded-2xl p-5 hover:border-red-500/40 transition-all duration-300",
  statCardBalance: "bg-gradient-to-br from-blue-500/10 to-gray-900 border border-blue-500/20 rounded-2xl p-5 hover:border-blue-500/40 transition-all duration-300",
  statCardUSD:     "bg-gradient-to-br from-amber-500/10 to-gray-900 border border-amber-500/20 rounded-2xl p-5 hover:border-amber-500/40 transition-all duration-300",

  statCardHeader: "flex items-center justify-between mb-4",
  statIconIngreso: "w-10 h-10 rounded-xl bg-emerald-500/20 flex items-center justify-center ring-1 ring-emerald-500/30 shadow-lg shadow-emerald-500/10",
  statIconGasto:   "w-10 h-10 rounded-xl bg-red-500/20 flex items-center justify-center ring-1 ring-red-500/30 shadow-lg shadow-red-500/10",
  statIconAmber:   "w-10 h-10 rounded-xl bg-amber-500/20 flex items-center justify-center ring-1 ring-amber-500/30 shadow-lg shadow-amber-500/10",
  statIconBluePos: "w-10 h-10 rounded-xl bg-blue-500/20 flex items-center justify-center ring-1 ring-blue-500/30 shadow-lg shadow-blue-500/10",
  statIconOrangeNeg: "w-10 h-10 rounded-xl bg-orange-500/20 flex items-center justify-center ring-1 ring-orange-500/30 shadow-lg shadow-orange-500/10",
  statChangePos: "flex items-center gap-1 text-xs font-semibold text-emerald-400 bg-emerald-500/10 px-2 py-0.5 rounded-full",
  statChangeNeg: "flex items-center gap-1 text-xs font-semibold text-red-400 bg-red-500/10 px-2 py-0.5 rounded-full",
  statLabel: "text-gray-400 text-xs font-medium uppercase tracking-wider",
  statValue: "text-white text-3xl font-bold mt-1 tracking-tight",
  statValueAmber: "text-amber-400 text-3xl font-bold mt-1 tracking-tight",
  statValueBalancePos: "text-3xl font-bold mt-1 tracking-tight text-blue-400",
  statValueBalanceNeg: "text-3xl font-bold mt-1 tracking-tight text-orange-400",
  statSub: "text-gray-600 text-xs mt-1",

  topCatCard: "bg-gray-900/60 backdrop-blur-sm border border-white/5 rounded-2xl p-6",
  topCatHeader: "flex items-center justify-between mb-5",
  topCatTitle: "text-white font-semibold",
  topCatMonth: "text-gray-600 text-xs capitalize bg-gray-800 px-2 py-1 rounded-lg",
  topCatGrid: "grid grid-cols-1 sm:grid-cols-2 gap-4",
  topCatRow: "space-y-1.5",
  topCatMeta: "flex items-center justify-between text-sm",
  topCatLeft: "flex items-center gap-2 min-w-0",
  topCatRank: "text-gray-600 text-xs w-4 flex-shrink-0 font-mono",
  topCatColorDot: "w-2.5 h-2.5 rounded-full flex-shrink-0",
  topCatName: "text-gray-300 truncate text-sm",
  topCatRight: "text-right flex-shrink-0 ml-2",
  topCatAmount: "text-white font-semibold text-sm",
  topCatPct: "text-gray-500 text-xs ml-1.5",
  topCatBar: "h-1.5 bg-gray-800 rounded-full overflow-hidden",
  topCatBarFill: "h-full rounded-full transition-all duration-700",
  topCatFooter: "mt-4 pt-4 border-t border-white/5 flex justify-between text-sm",
  topCatFooterLabel: "text-gray-500",
  topCatFooterValue: "text-red-400 font-semibold",

  alertsCard: "bg-gray-900/60 backdrop-blur-sm border border-white/5 rounded-2xl p-6",
  alertsHeader: "flex items-center gap-2 mb-5",
  alertsTitle: "text-white font-semibold",
  alertsMonth: "ml-auto text-gray-600 text-xs capitalize",
  alertsGrid: "grid grid-cols-1 sm:grid-cols-2 gap-3",
  alertItemSpike:     "border border-red-500/20 bg-gradient-to-br from-red-500/5 to-transparent rounded-xl p-4 space-y-2",
  alertItemHighShare: "border border-amber-500/20 bg-gradient-to-br from-amber-500/5 to-transparent rounded-xl p-4 space-y-2",
  alertItemNew:       "border border-blue-500/20 bg-gradient-to-br from-blue-500/5 to-transparent rounded-xl p-4 space-y-2",
  alertItemRow: "flex items-center gap-2",
  alertItemDot: "w-2.5 h-2.5 rounded-full flex-shrink-0",
  alertItemCat: "text-white font-medium text-sm",
  alertIconSpike:     "w-4 h-4 ml-auto flex-shrink-0 text-red-400",
  alertIconHighShare: "w-4 h-4 ml-auto flex-shrink-0 text-amber-400",
  alertIconNew:       "w-4 h-4 ml-auto flex-shrink-0 text-blue-400",
  alertMsgSpike:     "text-xs font-semibold text-red-400",
  alertMsgHighShare: "text-xs font-semibold text-amber-400",
  alertMsgNew:       "text-xs font-semibold text-blue-400",
  alertAmounts: "flex items-center justify-between text-xs text-gray-500",
  alertSuggestion: "text-gray-600 text-xs",

  bottomGrid: "grid grid-cols-1 lg:grid-cols-3 gap-6",
  recentCard: "lg:col-span-2 bg-gray-900/60 backdrop-blur-sm border border-white/5 rounded-2xl p-6",
  recentHeader: "flex items-center justify-between mb-5",
  recentTitle: "text-white font-semibold",
  recentLink: "text-emerald-400 hover:text-emerald-300 text-sm font-medium transition-colors",
  emptyWrap: "flex flex-col items-center justify-center py-10 text-center",
  emptyText: "text-gray-500 text-sm",
  emptyLink: "mt-3 text-emerald-400 hover:text-emerald-300 text-sm font-medium transition-colors",
  txList: "space-y-1",
  txRow: "flex items-center gap-3 p-3 rounded-xl hover:bg-white/5 transition-all duration-150 group cursor-default",
  txIconWrap: "w-9 h-9 rounded-xl flex items-center justify-center flex-shrink-0",
  txIconDot: "w-2.5 h-2.5 rounded-full",
  txMeta: "flex-1 min-w-0",
  txDesc: "text-white text-sm font-medium truncate",
  txSub: "text-gray-600 text-xs",
  txAmountIngreso: "text-sm font-bold flex-shrink-0 text-emerald-400",
  txAmountGasto:   "text-sm font-bold flex-shrink-0 text-red-400",

  quickStats: "space-y-4",
  thisMonthCard: "bg-gray-900/60 backdrop-blur-sm border border-white/5 rounded-2xl p-5",
  thisMonthTitle: "text-white font-semibold mb-4",
  thisMonthInner: "space-y-3",
  progressMeta: "flex justify-between text-sm mb-1.5",
  progressLabel: "text-gray-400 text-xs",
  progressValue: "text-gray-300 text-xs font-semibold",
  progressBar: "h-2 bg-gray-800 rounded-full overflow-hidden",
  progressFillGood: "h-full rounded-full transition-all duration-700 bg-gradient-to-r from-emerald-500 to-teal-400",
  progressFillBad:  "h-full rounded-full transition-all duration-700 bg-gradient-to-r from-red-500 to-orange-500",
  miniGrid: "grid grid-cols-2 gap-3 pt-2",
  miniCard: "bg-gray-800/50 rounded-xl p-3 border border-white/5",
  miniLabel: "text-gray-500 text-xs mb-1",
  miniValue: "text-white font-bold text-xl",
  miniSurplusPos: "font-bold text-lg text-emerald-400",
  miniSurplusNeg: "font-bold text-lg text-gray-600",

  dolarCard: "bg-gradient-to-br from-amber-500/8 to-gray-900 border border-amber-500/20 rounded-2xl p-5",
  dolarHeader: "flex items-center justify-between mb-3",
  dolarTitle: "text-white font-semibold",
  dolarLink: "text-emerald-400 hover:text-emerald-300 text-xs font-medium transition-colors",
  dolarRow: "flex justify-between items-end",
  dolarBuyLabel: "text-gray-500 text-xs",
  dolarBuyValue: "text-white font-semibold",
  dolarSellLabel: "text-gray-500 text-xs",
  dolarSellValue: "text-amber-400 font-bold text-2xl tracking-tight",
}
