export const S = {
  root: "min-h-screen bg-gray-900 flex items-center justify-center p-4",
  bgDecor: "absolute inset-0 overflow-hidden pointer-events-none",
  bgBlobTR: "absolute -top-40 -right-40 w-96 h-96 rounded-full bg-emerald-500/5 blur-3xl",
  bgBlobBL: "absolute -bottom-40 -left-40 w-96 h-96 rounded-full bg-emerald-500/5 blur-3xl",
  content: "relative w-full max-w-md",
  logoWrap: "flex flex-col items-center mb-8",
  logoIcon: "w-14 h-14 rounded-2xl bg-emerald-500 flex items-center justify-center shadow-xl shadow-emerald-500/30 mb-4",
  appName: "text-white text-2xl font-bold",
  tagline: "text-gray-400 text-sm mt-1",
  card: "bg-gray-800/60 border border-gray-700/50 rounded-2xl p-8 backdrop-blur-sm shadow-2xl",
  form: "space-y-5",
  label: "block text-sm font-medium text-gray-300 mb-2",
  inputWrap: "relative",
  input: "w-full pl-10 pr-4 py-3 bg-gray-700/50 border border-gray-600 rounded-xl text-white placeholder-gray-500 focus:outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500/30 transition-colors",
  inputWithToggle: "w-full pl-10 pr-12 py-3 bg-gray-700/50 border border-gray-600 rounded-xl text-white placeholder-gray-500 focus:outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500/30 transition-colors",
  inputIcon: "absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500",
  toggleBtn: "absolute right-0 top-0 h-full px-3 flex items-center text-gray-500 hover:text-gray-300 transition-colors",
  errorWrap: "bg-red-500/10 border border-red-500/20 rounded-xl px-4 py-3",
  errorText: "text-red-400 text-sm",
  submitBtn: "w-full py-3 px-4 bg-emerald-500 hover:bg-emerald-400 disabled:opacity-60 text-white font-semibold rounded-xl transition-colors flex items-center justify-center gap-2 shadow-lg shadow-emerald-500/20",
  footer: "mt-6 text-center",
  footerText: "text-gray-400 text-sm",
  footerLink: "text-emerald-400 hover:text-emerald-300 font-medium transition-colors",
}
