export const ClassNames = {
  overlay: "fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm",
  modal: "bg-gray-800 border border-gray-700 rounded-2xl w-full max-w-md shadow-2xl",
  header: "flex items-center justify-between px-6 py-4 border-b border-gray-700",
  headerTitle: "text-white font-semibold text-lg",
  closeBtn: "p-1.5 rounded-lg text-gray-400 hover:text-white hover:bg-gray-700 transition-colors",
  form: "p-6 space-y-5",
  label: "block text-sm font-medium text-gray-300 mb-2",
  typeGrid: "grid grid-cols-2 gap-2",
  typeBtnBase: "py-2.5 px-4 rounded-xl text-sm font-medium transition-all",
  typeBtnIngreso: "bg-emerald-500/20 text-emerald-400 border border-emerald-500/50",
  typeBtnGasto: "bg-red-500/20 text-red-400 border border-red-500/50",
  typeBtnInactive: "bg-gray-700/50 text-gray-400 border border-transparent hover:border-gray-600",
  amountRow: "flex gap-2",
  currencyToggle: "flex rounded-xl overflow-hidden border border-gray-600 shrink-0",
  currencyBtnArsActive: "px-3 py-2 text-sm font-medium bg-emerald-500/20 text-emerald-400 border-r border-gray-600",
  currencyBtnUsdActive: "px-3 py-2 text-sm font-medium bg-blue-500/20 text-blue-400 border-r border-gray-600",
  currencyBtnInactive: "px-3 py-2 text-sm font-medium text-gray-500 hover:text-gray-300 transition-colors border-r border-gray-600 last:border-r-0",
  amountWrap: "relative flex-1",
  amountPrefix: "absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 font-medium text-sm",
  amountInput: "w-full pl-10 pr-4 py-2.5 bg-gray-700/50 border border-gray-600 rounded-xl text-white placeholder-gray-500 focus:outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500/30 transition-colors",
  input: "w-full px-4 py-2.5 bg-gray-700/50 border border-gray-600 rounded-xl text-white placeholder-gray-500 focus:outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500/30 transition-colors",
  dateInput: "w-full px-4 py-2.5 bg-gray-700/50 border border-gray-600 rounded-xl text-white focus:outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500/30 transition-colors [color-scheme:dark]",
  select: "w-full px-4 py-2.5 bg-gray-700/50 border border-gray-600 rounded-xl text-white focus:outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500/30 transition-colors",
  error: "text-red-400 text-sm bg-red-500/10 border border-red-500/20 rounded-lg px-3 py-2",
  actions: "flex gap-3 pt-1",
  cancelBtn: "flex-1 py-2.5 px-4 rounded-xl border border-gray-600 text-gray-300 hover:bg-gray-700/50 transition-colors text-sm font-medium",
  submitBtn: "flex-1 py-2.5 px-4 rounded-xl bg-emerald-500 hover:bg-emerald-400 disabled:opacity-60 text-white font-medium text-sm transition-colors flex items-center justify-center gap-2",
}
