export const ClassNames = {
  root: "space-y-6 animate-fade-in-up",
  pageHeader: "flex items-start justify-between",
  pageTitle: "text-white text-2xl font-bold",
  pageSub: "text-gray-400 text-sm mt-1 flex items-center gap-2",
  pageSubLink: "text-emerald-400 hover:text-emerald-300 transition-colors",
  lastUpdatedWrap: "text-right",
  lastUpdatedLabel: "text-gray-500 text-xs",
  lastUpdatedValue: "text-gray-300 text-sm capitalize",
  ratesGrid: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-4",
  spreadCard: "bg-gray-800/50 border border-gray-700/50 rounded-2xl p-6",
  spreadTitle: "text-white font-semibold mb-4 flex items-center gap-2",
  spreadGrid: "grid grid-cols-2 sm:grid-cols-4 gap-4",
  spreadItem: "bg-gray-700/30 rounded-xl p-4",
  spreadItemLabel: "text-gray-400 text-xs mb-2",
  spreadItemSub: "text-gray-500 text-xs mt-1",
  usdCard: "bg-gray-800/50 border border-gray-700/50 rounded-2xl p-6",
  usdTitle: "text-white font-semibold mb-1 flex items-center gap-2",
  usdSub: "text-gray-400 text-sm mb-5",
  usdSurplusPos: "font-semibold text-emerald-400",
  usdSurplusNeg: "font-semibold text-gray-500",
  noSurplusBox: "flex items-start gap-3 bg-amber-500/10 border border-amber-500/20 rounded-xl p-4",
  noSurplusText: "text-amber-300 text-sm",
  usdGrid: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4",
  usdItem: "border rounded-xl p-4",
  usdItemLabel: "text-gray-400 text-xs mb-2",
  usdItemSub: "text-gray-500 text-xs mt-1",
  usdFootnote: "mt-4 flex items-start gap-2 text-gray-600 text-xs",
}
