export const ClassNames = {
  skeleton: "bg-gray-800/50 border border-gray-700/50 rounded-2xl p-5 animate-pulse",
  skeletonTitle: "h-4 bg-gray-700 rounded w-24 mb-3",
  skeletonValue: "h-8 bg-gray-700 rounded w-32 mb-2",
  skeletonSub: "h-4 bg-gray-700 rounded w-20",
  cardBase: "relative bg-gray-800/50 border rounded-2xl p-5 transition-all duration-200 hover:border-emerald-500/30 hover:shadow-lg hover:shadow-emerald-500/5",
  cardHighlight: "border-emerald-500/40 shadow-md shadow-emerald-500/10",
  cardDefault: "border-gray-700/50",
  badge: "absolute top-3 right-3 text-xs bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 px-2 py-0.5 rounded-full",
  title: "text-gray-400 text-sm font-medium mb-3",
  rows: "space-y-2",
  row: "flex items-center justify-between",
  label: "text-gray-500 text-xs",
  valueDefault: "text-white font-semibold",
  valueHighlight: "font-bold text-lg text-emerald-400",
  valueNormal: "font-bold text-lg text-white",
  divider: "pt-2 border-t border-gray-700/50 flex items-center justify-between",
  spread: "flex items-center gap-1 text-amber-400 text-xs",
  updatedAt: "mt-3 text-gray-600 text-xs truncate",
}
