export const ClassNames = {
  root: "space-y-6",
  pageHeader: "flex items-center justify-between",
  pageTitle: "text-white text-2xl font-bold",
  pageSub: "text-gray-400 text-sm mt-1",
  newBtn: "flex items-center gap-2 px-4 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-white text-sm font-medium transition-colors shadow-lg shadow-emerald-500/20",
  infoBanner: "bg-blue-500/10 border border-blue-500/20 rounded-xl p-4 text-blue-300 text-sm",
  skeletonList: "space-y-3",
  skeletonCard: "h-16 bg-gray-800 rounded-2xl animate-pulse",
  emptyWrap: "text-center py-16 text-gray-500",
  emptyCreateLink: "mt-4 text-emerald-400 hover:text-emerald-300 text-sm underline",
  listOuter: "space-y-6",
  sectionTitle: "text-gray-400 text-xs font-semibold uppercase tracking-wider mb-3",
  sectionList: "space-y-2",
  itemActive: "bg-gray-800/50 border border-gray-700/50 rounded-2xl px-5 py-4 flex items-center gap-4 transition-opacity",
  itemInactive: "bg-gray-800/50 border border-gray-700/20 rounded-2xl px-5 py-4 flex items-center gap-4 transition-opacity opacity-50",
  itemDot: "w-3 h-3 rounded-full flex-shrink-0",
  itemInfo: "flex-1 min-w-0",
  itemName: "text-white font-medium text-sm truncate",
  itemMeta: "text-gray-500 text-xs mt-0.5",
  itemEndDateExpired: "ml-1 text-red-400",
  itemEndDateFuture: "ml-1 text-amber-400",
  itemAmountIngreso: "font-semibold text-sm flex-shrink-0 text-emerald-400",
  itemAmountGasto: "font-semibold text-sm flex-shrink-0 text-red-400",
  itemActions: "flex items-center gap-1 flex-shrink-0",
  runNowBtn: "p-1.5 rounded-lg text-gray-500 hover:text-emerald-400 hover:bg-emerald-500/10 transition-colors",
  toggleBtn: "p-1.5 rounded-lg text-gray-500 hover:text-blue-400 hover:bg-blue-500/10 transition-colors",
  editBtn: "p-1.5 rounded-lg text-gray-500 hover:text-blue-400 hover:bg-blue-500/10 transition-colors",
  deleteConfirmWrap: "flex items-center gap-1",
  deleteConfirmYes: "px-2 py-1 rounded-md text-xs bg-red-500/20 text-red-400 hover:bg-red-500/30 transition-colors",
  deleteConfirmNo: "px-2 py-1 rounded-md text-xs bg-gray-700 text-gray-400",
  deleteBtn: "p-1.5 rounded-lg text-gray-500 hover:text-red-400 hover:bg-red-500/10 transition-colors",
  modalOverlay: "fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4",
  modalBox: "bg-gray-800 border border-gray-700 rounded-2xl p-6 w-full max-w-md shadow-xl",
  modalHeader: "flex items-center justify-between mb-5",
  modalTitle: "text-white font-semibold text-lg",
  modalCloseBtn: "text-gray-500 hover:text-white",
  modalFields: "space-y-4",
  typeToggleWrap: "flex rounded-xl overflow-hidden border border-gray-700",
  typeToggleIngresoActive: "flex-1 py-2.5 text-sm font-medium transition-colors bg-emerald-500 text-white",
  typeToggleGastoActive: "flex-1 py-2.5 text-sm font-medium transition-colors bg-red-500 text-white",
  typeToggleInactive: "flex-1 py-2.5 text-sm font-medium transition-colors text-gray-400 hover:text-white",
  fieldLabel: "text-gray-400 text-sm mb-1.5 block",
  input: "w-full px-4 py-2.5 bg-gray-700/50 border border-gray-600 rounded-xl text-white placeholder-gray-500 focus:outline-none focus:border-emerald-500 text-sm",
  select: "w-full px-4 py-2.5 bg-gray-700/50 border border-gray-600 rounded-xl text-white focus:outline-none focus:border-emerald-500 text-sm",
  endDateLabel: "text-gray-400 text-sm mb-1.5 block flex items-center gap-1.5",
  clearEndDateBtn: "text-xs text-gray-500 hover:text-red-400 mt-1 transition-colors",
  modalActions: "flex gap-3 mt-6",
  cancelBtn: "flex-1 py-2.5 rounded-xl border border-gray-600 text-gray-300 hover:bg-gray-700 text-sm transition-colors",
  saveBtn: "flex-1 py-2.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-white text-sm font-medium transition-colors disabled:opacity-50",
  toastOk: "fixed bottom-6 right-6 flex items-center gap-2 px-4 py-3 rounded-xl shadow-xl text-sm font-medium z-50 bg-emerald-500 text-white",
  toastErr: "fixed bottom-6 right-6 flex items-center gap-2 px-4 py-3 rounded-xl shadow-xl text-sm font-medium z-50 bg-red-500 text-white",
}
