export const S = {
  inner: "flex flex-col h-full",
  logoWrap: "flex items-center gap-3 px-6 py-6 border-b border-gray-700",
  logoIcon: "w-9 h-9 rounded-xl bg-emerald-500 flex items-center justify-center shadow-lg shadow-emerald-500/30",
  logoTitle: "text-white font-bold text-lg leading-none",
  logoSub: "text-gray-400 text-xs mt-0.5",
  nav: "flex-1 px-3 py-4 space-y-1",
  navLinkActive: "bg-emerald-500/20 text-emerald-400 shadow-sm",
  navLinkInactive: "text-gray-400 hover:bg-gray-700/50 hover:text-gray-200",
  navLinkBase: "flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-medium transition-all duration-200",
  navIconActive: "text-emerald-400",
  navIconInactive: "text-gray-500",
  navIconBase: "w-5 h-5 flex-shrink-0",
  navActiveDot: "ml-auto w-1.5 h-1.5 rounded-full bg-emerald-400",
  footer: "px-3 pb-4 border-t border-gray-700 pt-3",
  footerEmail: "px-3 py-2 mb-2",
  footerEmailText: "text-gray-500 text-xs truncate",
  logoutBtn: "flex items-center gap-3 w-full px-3 py-2.5 rounded-xl text-sm font-medium text-gray-400 hover:bg-red-500/10 hover:text-red-400 transition-all duration-200",
  mobileToggle: "lg:hidden fixed top-4 left-4 z-40 p-2 rounded-lg bg-gray-800 text-gray-300 shadow-lg",
  mobileOverlay: "lg:hidden fixed inset-0 z-40 bg-black/60 backdrop-blur-sm",
  mobileSidebarOpen: "lg:hidden fixed inset-y-0 left-0 z-50 w-64 bg-gray-900 border-r border-gray-700/50 transform transition-transform duration-300 translate-x-0",
  mobileSidebarClosed: "lg:hidden fixed inset-y-0 left-0 z-50 w-64 bg-gray-900 border-r border-gray-700/50 transform transition-transform duration-300 -translate-x-full",
  mobileCloseBtn: "absolute top-4 right-4 p-1.5 rounded-lg text-gray-400 hover:text-white hover:bg-gray-700",
  desktopSidebar: "hidden lg:flex flex-col fixed inset-y-0 left-0 z-30 w-64 bg-gray-900 border-r border-gray-700/50",
}
