export const ClassNames = {
  inner: "flex flex-col h-full",
  logoWrap: "flex items-center gap-3 px-6 py-6 border-b border-white/5",
  logoIcon: "w-9 h-9 rounded-xl bg-gradient-to-br from-emerald-400 to-teal-600 flex items-center justify-center shadow-lg shadow-emerald-500/40",
  logoTitle: "text-white font-bold text-lg leading-none tracking-tight",
  logoSub: "text-emerald-400/70 text-xs mt-0.5 font-medium",
  nav: "flex-1 px-3 py-4 space-y-0.5",
  navLinkActive: "bg-gradient-to-r from-emerald-500/15 to-transparent text-emerald-400 border-l-2 border-emerald-500",
  navLinkInactive: "text-gray-500 hover:bg-white/5 hover:text-gray-200 border-l-2 border-transparent",
  navLinkBase: "flex items-center gap-3 px-3 py-2.5 rounded-r-xl text-sm font-medium transition-all duration-200",
  navIconActive: "text-emerald-400",
  navIconInactive: "text-gray-600",
  navIconBase: "w-5 h-5 flex-shrink-0",
  navActiveDot: "ml-auto w-1.5 h-1.5 rounded-full bg-emerald-400 shadow-sm shadow-emerald-400/50",
  footer: "px-3 pb-4 border-t border-white/5 pt-3",
  footerEmail: "px-3 py-2 mb-2",
  footerEmailText: "text-gray-600 text-xs truncate",
  logoutBtn: "flex items-center gap-3 w-full px-3 py-2.5 rounded-xl text-sm font-medium text-gray-500 hover:bg-red-500/10 hover:text-red-400 transition-all duration-200",
  mobileToggle: "lg:hidden fixed top-4 left-4 z-40 p-2 rounded-xl bg-gray-900/90 backdrop-blur text-gray-300 shadow-xl border border-white/10",
  mobileOverlay: "lg:hidden fixed inset-0 z-40 bg-black/70 backdrop-blur-sm",
  mobileSidebarOpen: "lg:hidden fixed inset-y-0 left-0 z-50 w-64 bg-gray-950 border-r border-white/5 transform transition-transform duration-300 translate-x-0",
  mobileSidebarClosed: "lg:hidden fixed inset-y-0 left-0 z-50 w-64 bg-gray-950 border-r border-white/5 transform transition-transform duration-300 -translate-x-full",
  mobileCloseBtn: "absolute top-4 right-4 p-1.5 rounded-lg text-gray-400 hover:text-white hover:bg-white/10",
  desktopSidebar: "hidden lg:flex flex-col fixed inset-y-0 left-0 z-30 w-64 bg-gray-950 border-r border-white/5",
}
