export const ClassNames = {
  root: "space-y-6 animate-fade-in-up",
  pageHeader: "flex flex-col sm:flex-row sm:items-center justify-between gap-4",
  pageTitle: "text-white text-2xl font-bold",
  monthNav: "flex items-center gap-2 mt-1",
  monthNavBtn: "p-1 rounded-lg text-gray-500 hover:text-white hover:bg-gray-700 transition-colors",
  monthNavBtnDisabled: "p-1 rounded-lg text-gray-500 hover:text-white hover:bg-gray-700 transition-colors disabled:opacity-30 disabled:cursor-not-allowed",
  monthLabel: "text-emerald-400 text-sm font-medium capitalize",
  todayBtn: "text-xs text-gray-500 hover:text-emerald-400 transition-colors ml-1",
  totalCount: "text-gray-600 text-xs ml-1",
  headerActions: "flex items-center gap-2 flex-wrap",
  fileInputHidden: "hidden",
  btnDuplicates: "flex items-center gap-2 px-3 py-2 rounded-xl border border-orange-600/50 text-orange-400 hover:bg-orange-500/10 text-sm transition-colors disabled:opacity-50",
  btnClearAll: "flex items-center gap-2 px-3 py-2 rounded-xl border border-red-600/50 text-red-400 hover:bg-red-500/10 text-sm transition-colors disabled:opacity-50",
  btnTemplate: "flex items-center gap-2 px-3 py-2 rounded-xl border border-gray-600 text-gray-300 hover:bg-gray-700/50 text-sm transition-colors",
  btnImport: "flex items-center gap-2 px-3 py-2 rounded-xl border border-gray-600 text-gray-300 hover:bg-gray-700/50 text-sm transition-colors disabled:opacity-50",
  btnReceipt: "flex items-center gap-2 px-3 py-2 rounded-xl border border-purple-600/50 text-purple-400 hover:bg-purple-500/10 text-sm transition-colors disabled:opacity-50",
  btnExport: "flex items-center gap-2 px-3 py-2 rounded-xl border border-gray-600 text-gray-300 hover:bg-gray-700/50 text-sm transition-colors",
  btnNew: "flex items-center gap-2 px-4 py-2 rounded-xl bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-400 hover:to-teal-400 text-white text-sm font-semibold transition-all shadow-lg shadow-emerald-500/25 active:scale-95",
  menuWrap: "relative",
  menuDropdown: "absolute right-0 top-10 z-30 w-48 bg-gray-800 border border-gray-700 rounded-xl shadow-xl overflow-hidden py-1 animate-slide-in-down",
  menuItem: "flex items-center gap-2.5 w-full px-3 py-2.5 text-sm text-gray-300 hover:bg-gray-700 hover:text-white transition-colors",
  btnLabel: "hidden sm:inline",
  filtersRow: "flex flex-col sm:flex-row gap-3",
  searchWrap: "relative flex-1",
  searchInput: "w-full pl-10 pr-4 py-2.5 bg-gray-800/50 border border-gray-700 rounded-xl text-white placeholder-gray-500 focus:outline-none focus:border-emerald-500 transition-colors text-sm",
  filterGroup: "flex items-center gap-2 flex-wrap",
  filterBtnAll: "bg-gray-700 text-white border border-gray-600",
  filterBtnIngreso: "bg-emerald-500/20 text-emerald-400 border border-emerald-500/40",
  filterBtnGasto: "bg-red-500/20 text-red-400 border border-red-500/40",
  filterBtnInactive: "text-gray-400 hover:text-white border border-transparent",
  filterBtnBase: "px-3 py-2 rounded-xl text-sm font-medium transition-all",
  catFilterWrap: "relative",
  catFilterBtnActive: "flex items-center gap-2 px-3 py-2 rounded-xl text-sm font-medium border transition-all bg-blue-500/20 text-blue-400 border-blue-500/40",
  catFilterBtnInactive: "flex items-center gap-2 px-3 py-2 rounded-xl text-sm font-medium border transition-all text-gray-400 hover:text-white border-transparent hover:border-gray-600",
  catDropdown: "absolute z-20 top-10 right-0 w-52 bg-gray-800 border border-gray-700 rounded-xl shadow-xl overflow-hidden animate-slide-in-down",
  catDropdownInner: "p-1 max-h-64 overflow-y-auto",
  catDropdownItemActive: "flex items-center gap-2 w-full px-3 py-2 rounded-lg text-sm transition-colors bg-gray-700 text-white",
  catDropdownItemInactive: "flex items-center gap-2 w-full px-3 py-2 rounded-lg text-sm transition-colors text-gray-400 hover:bg-gray-700 hover:text-white",
  catDropdownDivider: "my-1 border-t border-gray-700",
  catDropdownDot: "w-2.5 h-2.5 rounded-full bg-gray-600 flex-shrink-0",
  catDropdownColorDot: "w-2.5 h-2.5 rounded-full flex-shrink-0",
  tableWrap: "bg-gray-900/60 backdrop-blur-sm border border-white/5 rounded-2xl overflow-hidden",
  tableScroll: "overflow-x-auto",
  table: "w-full",
  thead: "border-b border-gray-700/50",
  th: "text-left px-4 py-3 text-gray-400 text-xs font-medium uppercase tracking-wider",
  thRight: "text-right px-4 py-3 text-gray-400 text-xs font-medium uppercase tracking-wider",
  thSortBtn: "flex items-center gap-1 hover:text-white transition-colors",
  trLoading: "border-b border-gray-700/30",
  tdLoading: "px-4 py-3",
  skeletonCell: "h-4 bg-gray-700 rounded animate-pulse",
  trEmpty: "",
  tdEmpty: "px-4 py-12 text-center text-gray-500",
  trData: "border-b border-white/5 hover:bg-white/5 transition-all duration-150",
  tdDate: "px-4 py-3 text-gray-300 text-sm whitespace-nowrap",
  tdType: "px-4 py-3",
  typeBadgeIngreso: "inline-flex px-2 py-0.5 rounded-md text-xs font-medium bg-emerald-500/15 text-emerald-400",
  typeBadgeGasto: "inline-flex px-2 py-0.5 rounded-md text-xs font-medium bg-red-500/15 text-red-400",
  tdCategory: "px-4 py-3",
  catCellRow: "flex items-center gap-2",
  catCellDot: "w-2.5 h-2.5 rounded-full flex-shrink-0",
  catCellName: "text-gray-300 text-sm",
  noCatWrap: "relative",
  noCatSpinner: "flex items-center gap-1.5 px-2 py-1 text-xs text-gray-500",
  noCatBtn: "px-2 py-1 rounded-lg border border-dashed border-gray-600 text-gray-500 hover:border-emerald-500 hover:text-emerald-400 transition-colors text-xs",
  quickCatDropdown: "absolute z-20 top-8 left-0 w-48 bg-gray-800 border border-gray-700 rounded-xl shadow-xl overflow-hidden",
  quickCatInner: "p-1 max-h-52 overflow-y-auto",
  quickCatItem: "flex items-center gap-2 w-full px-3 py-2 rounded-lg hover:bg-gray-700 text-left text-sm text-gray-300 hover:text-white transition-colors",
  quickCatDot: "w-2.5 h-2.5 rounded-full flex-shrink-0",
  tdDesc: "px-4 py-3 text-gray-300 text-sm max-w-[200px] truncate",
  tdDescEmpty: "text-gray-600",
  tdAmount: "px-4 py-3 text-right",
  currencyBadgeUsd: "ml-1.5 inline-block px-1.5 py-0.5 rounded text-[10px] font-semibold bg-blue-500/15 text-blue-400 align-middle",
  currencyBadgeArs: "ml-1.5 inline-block px-1.5 py-0.5 rounded text-[10px] font-semibold bg-gray-700 text-gray-500 align-middle",
  amountIngreso: "font-semibold text-sm text-emerald-400",
  amountGasto: "font-semibold text-sm text-red-400",
  tdActions: "px-4 py-3",
  actionsWrap: "flex items-center justify-end gap-1",
  shareBtn: "p-1.5 rounded-lg text-gray-500 hover:text-emerald-400 hover:bg-emerald-500/10 transition-colors",
  editBtn: "p-1.5 rounded-lg text-gray-500 hover:text-blue-400 hover:bg-blue-500/10 transition-colors",
  deleteConfirmWrap: "flex items-center gap-1",
  deleteConfirmYes: "px-2 py-1 rounded-md text-xs bg-red-500/20 text-red-400 hover:bg-red-500/30 transition-colors",
  deleteConfirmNo: "px-2 py-1 rounded-md text-xs bg-gray-700 text-gray-400 hover:bg-gray-600 transition-colors",
  deleteBtn: "p-1.5 rounded-lg text-gray-500 hover:text-red-400 hover:bg-red-500/10 transition-colors",
  pagination: "flex items-center justify-between px-4 py-3 border-t border-gray-700/50",
  paginationInfo: "text-gray-500 text-sm",
  paginationControls: "flex items-center gap-2",
  paginationBtn: "p-1.5 rounded-lg text-gray-400 hover:text-white hover:bg-gray-700/50 disabled:opacity-40 disabled:cursor-not-allowed transition-colors",
  paginationLabel: "text-gray-400 text-sm",
  modalOverlay: "fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4 animate-fade-in",
  modalBox: "bg-gray-800 border border-gray-700 rounded-2xl p-6 w-full max-w-md shadow-xl animate-scale-in",
  modalHeader: "flex items-center justify-between mb-4",
  modalTitle: "text-white font-semibold text-lg",
  modalCloseBtn: "text-gray-500 hover:text-white",
  importResultRow: "flex items-center gap-3 p-4 rounded-xl bg-gray-700/50 mb-4",
  importResultText: "text-white font-medium",
  importResultSub: "text-gray-400 text-sm",
  importErrorBox: "bg-red-500/10 border border-red-500/20 rounded-xl p-3 max-h-48 overflow-y-auto",
  importErrorLabel: "text-red-400 text-xs font-medium mb-2",
  importErrorItem: "text-red-300 text-xs mb-1",
  importTip: "text-gray-500 text-xs mt-4",
  importCloseBtn: "mt-4 w-full py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-white text-sm font-medium transition-colors",
  receiptTitle: "text-white font-semibold text-lg flex items-center gap-2",
  receiptRows: "space-y-3 mb-5",
  receiptRow: "flex justify-between items-center py-2 border-b border-gray-700",
  receiptLabel: "text-gray-400 text-sm",
  receiptDateInput: "bg-gray-700 text-white text-sm rounded-lg px-2 py-1 border border-gray-600 focus:outline-none focus:border-purple-500",
  receiptDescInput: "bg-gray-700 text-white text-sm rounded-lg px-2 py-1 border border-gray-600 focus:outline-none focus:border-purple-500 w-48 text-right",
  receiptAmountInput: "bg-gray-700 text-white text-sm rounded-lg px-2 py-1 border border-gray-600 focus:outline-none focus:border-purple-500 w-32 text-right",
  receiptTypeRow: "flex justify-between items-center py-2",
  receiptTypeButtons: "flex gap-2",
  receiptTypeBtnGastoActive: "px-3 py-1 rounded-lg text-xs font-medium transition-colors bg-red-500/20 text-red-400 border border-red-500/40",
  receiptTypeBtnIngresoActive: "px-3 py-1 rounded-lg text-xs font-medium transition-colors bg-emerald-500/20 text-emerald-400 border border-emerald-500/40",
  receiptTypeBtnInactive: "px-3 py-1 rounded-lg text-xs font-medium transition-colors bg-gray-700 text-gray-400 border border-gray-600",
  receiptActions: "flex gap-3",
  receiptCancelBtn: "flex-1 py-2.5 rounded-xl border border-gray-600 text-gray-300 hover:bg-gray-700 text-sm transition-colors",
  receiptConfirmBtn: "flex-1 py-2.5 rounded-xl bg-purple-600 hover:bg-purple-500 text-white text-sm font-medium transition-colors",
  cleanModalBox: "bg-gray-800 border border-gray-700 rounded-2xl p-6 w-full max-w-sm shadow-xl text-center",
  cleanSuccessIcon: "w-14 h-14 rounded-full bg-emerald-500/15 flex items-center justify-center mx-auto mb-4",
  cleanNoneIcon: "w-14 h-14 rounded-full bg-blue-500/15 flex items-center justify-center mx-auto mb-4",
  cleanTitle: "text-white font-semibold text-lg mb-1",
  cleanText: "text-gray-400 text-sm",
  cleanOkBtn: "mt-5 w-full py-2.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-white text-sm font-medium transition-colors",
  clearAllIcon: "w-14 h-14 rounded-full bg-red-500/15 flex items-center justify-center mx-auto mb-4",
  clearAllActions: "flex gap-3 mt-5",
  clearAllCancelBtn: "flex-1 py-2.5 rounded-xl border border-gray-600 text-gray-300 hover:bg-gray-700 text-sm transition-colors disabled:opacity-50",
  clearAllConfirmBtn: "flex-1 py-2.5 rounded-xl bg-red-600 hover:bg-red-500 text-white text-sm font-medium transition-colors disabled:opacity-50",
}
